-- =============================================================
-- ハイカーズカード 現行スキーマ（2026-09-28 本番DBから復元 ＋ Step 17〜26 適用後）
--
-- 本番の Supabase から書き出した定義をもとに、1本にまとめたもの。
-- これまでの差分SQL（phase15 / report-block / mountains-* / affinity /
-- fix-favorite など）と step17〜step26 をすべて適用した後の状態に相当する。
--
-- 用途：
--   ・今後の開発の「正」となる参照資料
--   ・新しい環境（検証用プロジェクトなど）を空の状態から作るとき
--
-- ※ 本番DBには実行しないこと。すでに存在するため、トリガーや
--    ポリシーの作成でエラーになる。本番の変更は差分SQLで行う。
-- ※ 山マスタ349座のデータは含まない（別途 Table Editor から
--    CSVで書き出して取り込む）。
-- =============================================================


-- ---------- ランダム文字列 ----------

-- 公開ID用（紛らわしい文字 l/1/o/0 を除いた31文字）
create or replace function public.random_public_id(len integer default 6)
returns text language sql as $$
  select string_agg(
    substr('abcdefghjkmnpqrstuvwxyz23456789',
           (floor(random() * 31) + 1)::int, 1), '')
  from generate_series(1, len);
$$;

-- 交換トークン用（英数字62文字）
create or replace function public.random_token(len integer default 16)
returns text language sql as $$
  select string_agg(
    substr('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
           (floor(random() * 62) + 1)::int, 1), '')
  from generate_series(1, len);
$$;


-- =============================================================
-- テーブル
-- =============================================================

-- ---------- 山マスタ（349座） ----------
create table public.mountains (
  id          smallint generated by default as identity primary key,
  name        text not null unique,
  kana        text not null,
  elevation   smallint,
  area        text,
  difficulty  smallint check (difficulty between 1 and 5),
  meizan_rank smallint check (meizan_rank in (100, 200, 300)),  -- null = その他
  region      text check (region in (
                'north', 'kita_alps', 'minami_alps', 'koshin',
                'kanto', 'tokai', 'west')),
  is_popular  boolean not null default false,
  prefs       text[] not null default '{}',   -- 都道府県（県境の山は複数）
  pref        text,                            -- 旧列。コードからは未使用
  popular_rank smallint                         -- よく登られている順（1が最上位）。値は hikers-card-step25.sql で付ける
);
create index mountains_kana_idx    on public.mountains (kana);
create index mountains_rank_idx    on public.mountains (meizan_rank);
create index mountains_region_idx  on public.mountains (region);
create index mountains_popular_idx on public.mountains (is_popular) where is_popular;

-- ---------- プロフィール（カードの中身） ----------
create table public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  public_id     text not null unique,
  card_no       integer,   -- カードづくり完成（onboarded_at）の時点で発行（Step 23）。protect_profile_fields を参照
  display_name  text not null default '' check (char_length(display_name) <= 20),
  comment       text check (char_length(comment) <= 120),
  type_code     text check (type_code ~ '^[A-Z]{4}$'),
  axis_pe       smallint check (axis_pe between 0 and 100),
  axis_sg       smallint check (axis_sg between 0 and 100),
  axis_lf       smallint check (axis_lf between 0 and 100),
  axis_ca       smallint check (axis_ca between 0 and 100),
  card_bg       text not null default 'snow'   -- カードの背景（Step 26）。山なみ・朝焼け・雲海・地形図・夜空は交換で解放
                  constraint profiles_card_bg_check check (card_bg in (
                    'snow', 'moss', 'sand', 'sky', 'sumi', 'ridge', 'morgen', 'unkai', 'topo', 'night')),
  sns_yamap     text check (char_length(sns_yamap)     <= 60),
  sns_yamareco  text check (char_length(sns_yamareco)  <= 60),
  sns_instagram text check (char_length(sns_instagram) <= 60),
  sns_x         text check (char_length(sns_x)         <= 60),
  vis_rank_100  boolean not null default true,
  vis_rank_200  boolean not null default true,
  vis_rank_300  boolean not null default true,
  vis_rank_other boolean not null default true,
  onboarded_at  timestamptz,   -- カードづくりを完成させた日時（complete_onboarding からだけ設定）
  is_tester     boolean not null default false,   -- テスト用アカウント（admin_set_tester からだけ設定。Step 24）
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create unique index profiles_card_no_idx on public.profiles (card_no);

-- カード番号の連番（画面からは進められない）
create sequence public.profiles_card_no_seq as integer;
revoke all on sequence public.profiles_card_no_seq from anon, authenticated;

-- ---------- 登った山（is_favorite = 行ってよかった山） ----------
create table public.climbed_mountains (
  user_id     uuid not null references public.profiles(id) on delete cascade,
  mountain_id smallint not null references public.mountains(id),
  is_favorite boolean not null default false,
  favorite_rank smallint check (favorite_rank between 1 and 5),   -- よかった山の順位
  created_at  timestamptz not null default now(),
  primary key (user_id, mountain_id)
);
create index climbed_favorite_idx on public.climbed_mountains (user_id) where is_favorite;
create unique index climbed_favorite_rank_uniq
  on public.climbed_mountains (user_id, favorite_rank) where favorite_rank is not null;

-- ---------- 登りたい山 ----------
create table public.wishlist_mountains (
  user_id     uuid not null references public.profiles(id) on delete cascade,
  mountain_id smallint not null references public.mountains(id),
  created_at  timestamptz not null default now(),
  primary key (user_id, mountain_id)
);

-- ---------- 交換トークン（10分有効のQR） ----------
create table public.exchange_tokens (
  token      text primary key,
  owner_id   uuid not null references public.profiles(id) on delete cascade,
  expires_at timestamptz not null,
  revoked    boolean not null default false,
  use_count  integer not null default 0,
  created_at timestamptz not null default now()
);
create index exchange_tokens_owner_idx on public.exchange_tokens (owner_id);

-- ---------- 交換の記録（1組1行、user_a < user_b） ----------
create table public.exchanges (
  id                uuid primary key default gen_random_uuid(),
  user_a            uuid not null references public.profiles(id) on delete cascade,
  user_b            uuid not null references public.profiles(id) on delete cascade,
  first_met_at      timestamptz not null default now(),
  last_exchanged_at timestamptz not null default now(),
  check (user_a < user_b),
  unique (user_a, user_b)
);

-- ---------- ブロック ----------
create table public.blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

-- ---------- 通報 ----------
create table public.reports (
  id          uuid primary key default gen_random_uuid(),
  reporter_id uuid references public.profiles(id) on delete set null,
  reported_id uuid not null references public.profiles(id) on delete cascade,
  reason      text not null,
  detail      text check (char_length(detail) <= 1000),
  status      text not null default 'open' check (status in ('open', 'resolved')),
  created_at  timestamptz not null default now()
);


-- =============================================================
-- RLS とポリシー
-- =============================================================

alter table public.mountains          enable row level security;
alter table public.profiles           enable row level security;
alter table public.climbed_mountains  enable row level security;
alter table public.wishlist_mountains enable row level security;
alter table public.exchange_tokens    enable row level security;
alter table public.exchanges          enable row level security;
alter table public.blocks             enable row level security;
alter table public.reports            enable row level security;

create policy "mountains readable" on public.mountains for select using (true);

create policy "own profile read"   on public.profiles for select using (auth.uid() = id);
create policy "own profile update" on public.profiles for update using (auth.uid() = id);

create policy "climbed read"   on public.climbed_mountains for select using (true);
create policy "climbed insert" on public.climbed_mountains for insert with check (auth.uid() = user_id);
create policy "climbed update" on public.climbed_mountains for update
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "climbed delete" on public.climbed_mountains for delete using (auth.uid() = user_id);

create policy "wishlist read"   on public.wishlist_mountains for select using (true);
create policy "wishlist insert" on public.wishlist_mountains for insert with check (auth.uid() = user_id);
create policy "wishlist update" on public.wishlist_mountains for update
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "wishlist delete" on public.wishlist_mountains for delete using (auth.uid() = user_id);

create policy "token read"   on public.exchange_tokens for select using (auth.uid() = owner_id);
create policy "token insert" on public.exchange_tokens for insert with check (auth.uid() = owner_id);
create policy "token revoke" on public.exchange_tokens for update using (auth.uid() = owner_id);

create policy "exchange read"   on public.exchanges for select
  using (auth.uid() = user_a or auth.uid() = user_b);
create policy "exchange delete" on public.exchanges for delete
  using (auth.uid() = user_a or auth.uid() = user_b);

create policy "blocks read"   on public.blocks for select using (auth.uid() = blocker_id);
create policy "blocks insert" on public.blocks for insert with check (auth.uid() = blocker_id);
create policy "blocks delete" on public.blocks for delete using (auth.uid() = blocker_id);

create policy "reports insert" on public.reports for insert
  with check (reporter_id is null or auth.uid() = reporter_id);


-- =============================================================
-- トリガー関数とトリガー
-- =============================================================

-- アカウント作成時に profiles 行を自動作成
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare new_id text;
begin
  loop
    new_id := public.random_public_id(6);
    exit when not exists (select 1 from public.profiles where public_id = new_id);
  end loop;
  insert into public.profiles (id, public_id) values (new.id, new_id);
  return new;
end;
$$;

-- ※ auth スキーマ側のトリガーなので、今回の書き出しには出ていない。
--    設計書 v1 の定義どおり存在する前提。
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 変更不可列の保護 ＋ updated_at 自動更新 ＋ 条件がそろったらカード番号を発行（Step 20）
create or replace function public.protect_profile_fields()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  need int;
begin
  new.updated_at := now();
  new.public_id  := old.public_id;   -- URLは変更不可
  new.card_no    := old.card_no;     -- カード番号も変更不可
  new.created_at := old.created_at;

  -- 完成の日時は、complete_onboarding が許可の印を立てたときだけ変えられる
  if coalesce(current_setting('hc.onboarding', true), '') <> '1' then
    new.onboarded_at := old.onboarded_at;
  end if;

  -- テスト用の印は、管理人（admin_set_tester）が許可の印を立てたときだけ変えられる
  if coalesce(current_setting('hc.tester', true), '') <> '1' then
    new.is_tester := old.is_tester;
  end if;

  -- カードの背景の鍵：交換した枚数が足りない背景には変えられない
  --   山なみ 1枚 ／ 朝焼け・雲海 3枚 ／ 地形図・夜空 5枚（card.js の THEMES と同じ表）
  --   いま使っている背景のまま（変えない）なら、枚数が足りなくてもそのまま使える
  if new.card_bg is distinct from old.card_bg then
    need := case new.card_bg
              when 'ridge'  then 1
              when 'morgen' then 3
              when 'unkai'  then 3
              when 'topo'   then 5
              when 'night'  then 5
              else 0 end;
    if need > 0 and (select count(*) from public.exchanges e
                      where new.id in (e.user_a, e.user_b)) < need then
      raise exception 'bg_locked';
    end if;
  end if;

  -- 完成したら、まだ番号の無い人に次の番号を振る
  if new.card_no is null and new.onboarded_at is not null then
    new.card_no := nextval('public.profiles_card_no_seq');
  end if;

  return new;
end;
$$;

create trigger on_profile_update
  before update on public.profiles
  for each row execute function public.protect_profile_fields();

-- 行ってよかった山は5座まで
create or replace function public.limit_favorites()
returns trigger language plpgsql as $$
begin
  if new.is_favorite and (
    select count(*) from public.climbed_mountains
     where user_id = new.user_id and is_favorite
       and mountain_id <> new.mountain_id
  ) >= 5 then
    raise exception 'favorite_limit';
  end if;
  return new;
end;
$$;

create trigger check_favorite_limit
  before insert or update on public.climbed_mountains
  for each row execute function public.limit_favorites();

-- 登りたい山は5座まで
create or replace function public.limit_wishlist()
returns trigger language plpgsql as $$
begin
  if (select count(*) from public.wishlist_mountains
       where user_id = new.user_id) >= 5 then
    raise exception 'wishlist_limit';
  end if;
  return new;
end;
$$;

create trigger check_wishlist_limit
  before insert on public.wishlist_mountains
  for each row execute function public.limit_wishlist();

-- ブロックしたら交換記録を削除
create or replace function public.on_block_created()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  delete from public.exchanges
   where (user_a = least(new.blocker_id, new.blocked_id)
      and user_b = greatest(new.blocker_id, new.blocked_id));
  return new;
end;
$$;

create trigger after_block_insert
  after insert on public.blocks
  for each row execute function public.on_block_created();


-- =============================================================
-- RPC
-- =============================================================

-- ---------- 名山ランク別の踏破数 ----------
create or replace function public.meizan_counts(p_user uuid)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    '100',   count(*) filter (where m.meizan_rank = 100),
    '200',   count(*) filter (where m.meizan_rank = 200),
    '300',   count(*) filter (where m.meizan_rank = 300),
    'other', count(*) filter (where m.meizan_rank is null)
  )
  from public.climbed_mountains c
  join public.mountains m on m.id = c.mountain_id
  where c.user_id = p_user;
$$;

-- ---------- 自分のカード（共通点の計算用） ----------
create or replace function public.get_my_card()
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  prof public.profiles%rowtype;
  cnt jsonb;
begin
  if me is null then return null; end if;

  select * into prof from public.profiles where id = me;
  if not found then return null; end if;

  cnt := public.meizan_counts(me);

  return jsonb_build_object(
    'public_id',    prof.public_id,
    'card_no',      prof.card_no,
    'display_name', prof.display_name,
    'comment',      prof.comment,
    'type_code',    prof.type_code,
    'card_bg',      prof.card_bg,
    'axes', jsonb_build_object(
      'pe', prof.axis_pe, 'sg', prof.axis_sg,
      'lf', prof.axis_lf, 'ca', prof.axis_ca),
    'ranks', cnt,
    'climbed',
      coalesce((select jsonb_agg(jsonb_build_object(
          'name', m.name, 'rank', m.meizan_rank)
          order by m.elevation desc nulls last)
        from public.climbed_mountains c
        join public.mountains m on m.id = c.mountain_id
       where c.user_id = me), '[]'::jsonb),
    'favorites',
      coalesce((select jsonb_agg(jsonb_build_object(
          'name', m.name, 'rank', m.meizan_rank, 'pos', c.favorite_rank)
          order by c.favorite_rank nulls last, m.elevation desc nulls last)
        from public.climbed_mountains c
        join public.mountains m on m.id = c.mountain_id
       where c.user_id = me and c.is_favorite), '[]'::jsonb),
    'wishlist',
      coalesce((select jsonb_agg(jsonb_build_object(
          'name', m.name, 'rank', m.meizan_rank)
          order by m.elevation desc nulls last)
        from public.wishlist_mountains w
        join public.mountains m on m.id = w.mountain_id
       where w.user_id = me), '[]'::jsonb)
  );
end;
$$;

-- ---------- 公開カード ----------
create or replace function public.get_public_card(p_public_id text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  prof public.profiles%rowtype;
  viewer uuid := auth.uid();
  result jsonb;
  sns jsonb;
  cnt jsonb;
  ranks jsonb;
begin
  select * into prof from public.profiles where public_id = p_public_id;
  if not found then return null; end if;
  if prof.onboarded_at is null then return null; end if;   -- 完成前のカードは公開しない

  -- 相手にブロックされていたら「存在しない」ことにする
  if viewer is not null and exists (
    select 1 from public.blocks
    where blocker_id = prof.id and blocked_id = viewer
  ) then
    return null;
  end if;

  -- SNSは入力のあるものだけ返す
  sns := '{}'::jsonb;
  if nullif(btrim(coalesce(prof.sns_yamap,     '')), '') is not null then
    sns := sns || jsonb_build_object('yamap', prof.sns_yamap); end if;
  if nullif(btrim(coalesce(prof.sns_yamareco,  '')), '') is not null then
    sns := sns || jsonb_build_object('yamareco', prof.sns_yamareco); end if;
  if nullif(btrim(coalesce(prof.sns_instagram, '')), '') is not null then
    sns := sns || jsonb_build_object('instagram', prof.sns_instagram); end if;
  if nullif(btrim(coalesce(prof.sns_x,         '')), '') is not null then
    sns := sns || jsonb_build_object('x', prof.sns_x); end if;

  -- 踏破数。公開設定がオンのものだけ含める
  cnt := public.meizan_counts(prof.id);
  ranks := '{}'::jsonb;
  if prof.vis_rank_100   then ranks := ranks || jsonb_build_object('100',   cnt->'100');   end if;
  if prof.vis_rank_200   then ranks := ranks || jsonb_build_object('200',   cnt->'200');   end if;
  if prof.vis_rank_300   then ranks := ranks || jsonb_build_object('300',   cnt->'300');   end if;
  if prof.vis_rank_other then ranks := ranks || jsonb_build_object('other', cnt->'other'); end if;

  result := jsonb_build_object(
    'public_id',    prof.public_id,
    'card_no',      prof.card_no,
    'display_name', prof.display_name,
    'comment',      prof.comment,
    'type_code',    prof.type_code,
    'card_bg',      prof.card_bg,
    'axes', jsonb_build_object(
      'pe', prof.axis_pe, 'sg', prof.axis_sg,
      'lf', prof.axis_lf, 'ca', prof.axis_ca),
    'sns', sns,
    'ranks', ranks,
    'climbed',
      coalesce((select jsonb_agg(jsonb_build_object(
          'name', m.name, 'rank', m.meizan_rank)
          order by m.elevation desc nulls last)
        from public.climbed_mountains c
        join public.mountains m on m.id = c.mountain_id
       where c.user_id = prof.id), '[]'::jsonb),
    'favorites',
      coalesce((select jsonb_agg(jsonb_build_object(
          'name', m.name, 'rank', m.meizan_rank, 'pos', c.favorite_rank)
          order by c.favorite_rank nulls last, m.elevation desc nulls last)
        from public.climbed_mountains c
        join public.mountains m on m.id = c.mountain_id
       where c.user_id = prof.id and c.is_favorite), '[]'::jsonb),
    'wishlist',
      coalesce((select jsonb_agg(jsonb_build_object(
          'name', m.name, 'rank', m.meizan_rank)
          order by m.elevation desc nulls last)
        from public.wishlist_mountains w
        join public.mountains m on m.id = w.mountain_id
       where w.user_id = prof.id), '[]'::jsonb)
  );

  if viewer is not null and viewer <> prof.id then
    result := result || jsonb_build_object('exchanged', exists (
      select 1 from public.exchanges
      where user_a = least(viewer, prof.id) and user_b = greatest(viewer, prof.id)));
  end if;

  return result;
end;
$$;

-- ---------- コレクション ----------
create or replace function public.get_my_collection()
returns jsonb language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid();
begin
  if me is null then raise exception 'not authenticated'; end if;

  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'public_id',    p.public_id,
      'card_no',      p.card_no,
      'display_name', p.display_name,
      'comment',      p.comment,
      'type_code',    p.type_code,
      'card_bg',      p.card_bg,
      'axes', jsonb_build_object(
        'pe', p.axis_pe, 'sg', p.axis_sg, 'lf', p.axis_lf, 'ca', p.axis_ca),
      'sns', (
        select coalesce(jsonb_object_agg(k, v), '{}'::jsonb)
        from (values
          ('yamap', p.sns_yamap), ('yamareco', p.sns_yamareco),
          ('instagram', p.sns_instagram), ('x', p.sns_x)
        ) as t(k, v)
        where nullif(btrim(coalesce(v, '')), '') is not null),
      'ranks', (
        select coalesce(jsonb_object_agg(k, v), '{}'::jsonb)
        from (values
          ('100',   case when p.vis_rank_100   then public.meizan_counts(p.id)->'100'   end),
          ('200',   case when p.vis_rank_200   then public.meizan_counts(p.id)->'200'   end),
          ('300',   case when p.vis_rank_300   then public.meizan_counts(p.id)->'300'   end),
          ('other', case when p.vis_rank_other then public.meizan_counts(p.id)->'other' end)
        ) as t(k, v)
        where v is not null),
      'climbed',
        coalesce((select jsonb_agg(jsonb_build_object(
            'name', m.name, 'rank', m.meizan_rank)
            order by m.elevation desc nulls last)
          from public.climbed_mountains c
          join public.mountains m on m.id = c.mountain_id
         where c.user_id = p.id), '[]'::jsonb),
      'favorites',
        coalesce((select jsonb_agg(jsonb_build_object(
            'name', m.name, 'rank', m.meizan_rank, 'pos', c.favorite_rank)
            order by c.favorite_rank nulls last, m.elevation desc nulls last)
          from public.climbed_mountains c
          join public.mountains m on m.id = c.mountain_id
         where c.user_id = p.id and c.is_favorite), '[]'::jsonb),
      'wishlist',
        coalesce((select jsonb_agg(jsonb_build_object(
            'name', m.name, 'rank', m.meizan_rank)
            order by m.elevation desc nulls last)
          from public.wishlist_mountains w
          join public.mountains m on m.id = w.mountain_id
         where w.user_id = p.id), '[]'::jsonb),
      'first_met_at', e.first_met_at
    ) order by e.first_met_at desc)
    from public.exchanges e
    join public.profiles p
      on p.id = case when e.user_a = me then e.user_b else e.user_a end
   where me in (e.user_a, e.user_b)
  ), '[]'::jsonb);
end;
$$;

-- ---------- 山の登録をまとめて保存（Step 17） ----------
-- p_favorites は配列の順番がそのまま1位〜5位
create or replace function public.save_my_mountains(
  p_climbed   smallint[],
  p_favorites smallint[],
  p_wishlist  smallint[])
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me   uuid := auth.uid();
  clim smallint[];
  fav  smallint[];
  wish smallint[];
begin
  if me is null then raise exception 'not authenticated'; end if;

  -- 重複を除く（よかった山は順番を保つ）
  select coalesce(array_agg(distinct x), '{}') into clim
    from unnest(coalesce(p_climbed, '{}')) as x;

  select coalesce(array_agg(x order by first_pos), '{}') into fav
    from (select x, min(ord) as first_pos
            from unnest(coalesce(p_favorites, '{}')) with ordinality as t(x, ord)
           group by x) s;

  select coalesce(array_agg(distinct x), '{}') into wish
    from unnest(coalesce(p_wishlist, '{}')) as x;

  -- 検証
  if cardinality(fav) > 5 then raise exception 'favorite_limit'; end if;
  if cardinality(wish) > 5 then raise exception 'wishlist_limit'; end if;
  if not (fav <@ clim) then raise exception 'favorite_not_climbed'; end if;

  -- 登りたい山のうち、登った山に入っているものは外す
  select coalesce(array_agg(x), '{}') into wish
    from unnest(wish) as x where x <> all(clim);

  -- 登った山：外したものを消し、足したものを入れる
  delete from public.climbed_mountains
   where user_id = me and mountain_id <> all(clim);

  insert into public.climbed_mountains (user_id, mountain_id)
  select me, x from unnest(clim) as x
  on conflict (user_id, mountain_id) do nothing;

  -- よかった山：いったん全部外してから、順位を付け直す
  update public.climbed_mountains
     set is_favorite = false, favorite_rank = null
   where user_id = me and (is_favorite or favorite_rank is not null);

  update public.climbed_mountains c
     set is_favorite = true, favorite_rank = f.ord
    from unnest(fav) with ordinality as f(id, ord)
   where c.user_id = me and c.mountain_id = f.id;

  -- 登りたい山：入れ直す
  delete from public.wishlist_mountains where user_id = me;

  insert into public.wishlist_mountains (user_id, mountain_id)
  select me, x from unnest(wish) as x;

  return jsonb_build_object(
    'ok', true,
    'climbed', cardinality(clim),
    'favorites', cardinality(fav),
    'wishlist', cardinality(wish));
end;
$$;

-- ---------- 交換トークンの発行 ----------
create or replace function public.issue_exchange_token()
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  t text;
  exp timestamptz := now() + interval '10 minutes';
begin
  if me is null then raise exception 'not authenticated'; end if;

  -- 表示名が未設定のうちは交換できない
  if (select onboarded_at from public.profiles where id = me) is null then   -- カードが完成していなければ交換できない
    raise exception 'profile not ready';
  end if;

  -- 既存の有効なトークンを無効化（同時に複数出さない）
  update public.exchange_tokens
     set revoked = true
   where owner_id = me and revoked = false and expires_at > now();

  loop
    t := public.random_token(16);
    exit when not exists (select 1 from public.exchange_tokens where token = t);
  end loop;

  insert into public.exchange_tokens (token, owner_id, expires_at)
  values (t, me, exp);

  return jsonb_build_object('token', t, 'expires_at', exp);
end;
$$;

-- ---------- 交換トークンの使用 ----------
create or replace function public.redeem_exchange_token(p_token text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  tok public.exchange_tokens%rowtype;
  a uuid; b uuid;
  is_new boolean;
begin
  if me is null then raise exception 'not authenticated'; end if;

  select * into tok from public.exchange_tokens where token = p_token;
  if not found then return jsonb_build_object('ok', false, 'reason', 'not_found'); end if;
  if tok.revoked then return jsonb_build_object('ok', false, 'reason', 'revoked'); end if;
  if tok.expires_at <= now() then return jsonb_build_object('ok', false, 'reason', 'expired'); end if;
  if tok.owner_id = me then return jsonb_build_object('ok', false, 'reason', 'self'); end if;

  -- どちらかがブロックしていたら交換できない
  if exists (
    select 1 from public.blocks
    where (blocker_id = tok.owner_id and blocked_id = me)
       or (blocker_id = me and blocked_id = tok.owner_id)
  ) then
    return jsonb_build_object('ok', false, 'reason', 'blocked');
  end if;

  -- 表示名が未設定なら交換できない
  if (select onboarded_at from public.profiles where id = me) is null then   -- カードが完成していなければ交換できない
    return jsonb_build_object('ok', false, 'reason', 'profile_not_ready');
  end if;

  a := least(me, tok.owner_id);
  b := greatest(me, tok.owner_id);

  insert into public.exchanges (user_a, user_b)
  values (a, b)
  on conflict (user_a, user_b)
    do update set last_exchanged_at = now()   -- first_met_at は上書きしない
  returning (xmax = 0) into is_new;

  update public.exchange_tokens
     set use_count = use_count + 1
   where token = p_token;

  -- 新しく交換できたら、QRを見せていた側に「交換しました」のお知らせを残す
  -- （読み取った側は、その場でお祝いの画面を見るので不要）
  if is_new then
    insert into public.notices (user_id, kind, partner_id)
    values (tok.owner_id, 'exchanged', me);
  end if;

  return jsonb_build_object(
    'ok', true,
    'is_new', is_new,
    'partner', (select public_id from public.profiles where id = tok.owner_id));
end;
$$;

-- ---------- 通報（あわせてブロックも可） ----------
create or replace function public.submit_report(
  p_public_id text, p_reason text,
  p_detail text default null, p_block boolean default false)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me     uuid := auth.uid();
  target uuid;
begin
  select id into target from public.profiles where public_id = p_public_id;
  if target is null then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;

  if me is not null and me = target then
    return jsonb_build_object('ok', false, 'reason', 'self');
  end if;

  if p_reason is null or btrim(p_reason) = '' then
    return jsonb_build_object('ok', false, 'reason', 'no_reason');
  end if;

  insert into public.reports (reporter_id, reported_id, reason, detail)
  values (me, target, p_reason, nullif(btrim(coalesce(p_detail, '')), ''));

  -- あわせてブロックする場合（ログインしているときだけ）
  if p_block and me is not null then
    insert into public.blocks (blocker_id, blocked_id)
    values (me, target)
    on conflict do nothing;
  end if;

  return jsonb_build_object('ok', true);
end;
$$;

-- ---------- ブロック ----------
create or replace function public.block_user(p_public_id text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me     uuid := auth.uid();
  target uuid;
begin
  if me is null then
    return jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  end if;

  select id into target from public.profiles where public_id = p_public_id;
  if target is null then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;
  if target = me then
    return jsonb_build_object('ok', false, 'reason', 'self');
  end if;

  insert into public.blocks (blocker_id, blocked_id)
  values (me, target)
  on conflict do nothing;

  return jsonb_build_object('ok', true);
end;
$$;

-- ---------- ブロック解除 ----------
create or replace function public.unblock_user(p_public_id text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me     uuid := auth.uid();
  target uuid;
begin
  if me is null then
    return jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  end if;

  select id into target from public.profiles where public_id = p_public_id;
  if target is null then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;

  delete from public.blocks
   where blocker_id = me and blocked_id = target;

  return jsonb_build_object('ok', true);
end;
$$;

-- ---------- ブロック中の一覧 ----------
create or replace function public.get_my_blocks()
returns jsonb language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid();
begin
  if me is null then
    raise exception 'not authenticated';
  end if;

  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'public_id',    p.public_id,
      'display_name', p.display_name,
      'type_code',    p.type_code,
      'card_no',      p.card_no,
      'blocked_at',   b.created_at
    ) order by b.created_at desc)
    from public.blocks b
    join public.profiles p on p.id = b.blocked_id
   where b.blocker_id = me
  ), '[]'::jsonb);
end;
$$;

-- （参考）rls_auto_enable は Supabase が自動で用意する関数で、
--  public に作ったテーブルのRLSを自動で有効にするもの。自作ではないので含めていない。


-- =============================================================
-- カードの裏面（Step 18）
-- =============================================================

-- ---------- 裏面の中身 ----------
--
-- skills は { "項目キー": { "level": 0〜5, "visible": true/false }, ... }
--   level 0 = 未経験、1〜5 = 段階。登録していない項目はキー自体が無い。
--   項目の一覧（キーと段階の目安）は card-back.js で管理している。
--   項目を増やすときにSQLを変えなくて済むよう、ここでは形だけを検証する。
create table public.card_backs (
  user_id    uuid primary key references public.profiles(id) on delete cascade,
  skills     jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.card_backs enable row level security;

-- 読むのは本人だけ（編集画面用）。
-- 書き込みは save_card_back 経由だけにするので、insert / update のポリシーは作らない。
-- 相手が見るときは get_card_back 経由（交換済みかどうかを確かめる）。
create policy "own back read" on public.card_backs
  for select using (auth.uid() = user_id);


-- ---------- 裏面を保存する ----------
create or replace function public.save_card_back(p_skills jsonb)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me    uuid := auth.uid();
  k     text;
  v     jsonb;
  lvl   int;
  clean jsonb := '{}'::jsonb;
begin
  if me is null then raise exception 'not authenticated'; end if;

  if p_skills is null or jsonb_typeof(p_skills) <> 'object' then
    raise exception 'invalid_skills';
  end if;

  if (select count(*) from jsonb_object_keys(p_skills)) > 40 then
    raise exception 'too_many_skills';
  end if;

  for k, v in select * from jsonb_each(p_skills) loop
    -- キーは英小文字・数字・_ のみ
    if k !~ '^[a-z][a-z0-9_]{1,30}$' then raise exception 'invalid_key'; end if;
    if jsonb_typeof(v) <> 'object' then raise exception 'invalid_value'; end if;
    if jsonb_typeof(v->'level') <> 'number' then raise exception 'invalid_level'; end if;

    lvl := (v->>'level')::numeric::int;
    if lvl < 0 or lvl > 5 or (v->>'level')::numeric <> lvl then
      raise exception 'invalid_level';
    end if;

    -- 必要なものだけを、決まった形で保存する
    clean := clean || jsonb_build_object(k, jsonb_build_object(
      'level', lvl,
      'visible', coalesce((v->>'visible')::boolean, true)));
  end loop;

  insert into public.card_backs (user_id, skills, updated_at)
  values (me, clean, now())
  on conflict (user_id) do update
    set skills = excluded.skills, updated_at = now();

  return jsonb_build_object('ok', true);
end;
$$;


-- ---------- 裏面を見る ----------
--
-- 返すもの：
--   null                                   … カードが無い／ブロック関係にある
--   { locked: true, reason: 'login' }      … 未ログイン
--   { locked: true, reason: 'not_exchanged' } … まだ交換していない
--   { locked: false, skills: {キー: 段階}, updated_at }
--      … 表示オンの項目だけ。本人が見ても同じ（相手からの見え方を確かめられる）
create or replace function public.get_card_back(p_public_id text)
returns jsonb language plpgsql stable security definer set search_path = public as $$
declare
  viewer uuid := auth.uid();
  prof   public.profiles%rowtype;
  back   public.card_backs%rowtype;
begin
  select * into prof from public.profiles where public_id = p_public_id;
  if not found or prof.onboarded_at is null then return null; end if;   -- 完成前のカードは公開しない

  if viewer is distinct from prof.id then
    if viewer is null then
      return jsonb_build_object('locked', true, 'reason', 'login');
    end if;

    -- どちらかがブロックしていたら、存在しないことにする
    if exists (
      select 1 from public.blocks
       where (blocker_id = prof.id and blocked_id = viewer)
          or (blocker_id = viewer and blocked_id = prof.id)
    ) then
      return null;
    end if;

    if not exists (
      select 1 from public.exchanges
       where user_a = least(viewer, prof.id) and user_b = greatest(viewer, prof.id)
    ) then
      return jsonb_build_object('locked', true, 'reason', 'not_exchanged');
    end if;
  end if;

  select * into back from public.card_backs where user_id = prof.id;

  return jsonb_build_object(
    'locked', false,
    'skills', coalesce((
      select jsonb_object_agg(key, (value->>'level')::int)
        from jsonb_each(coalesce(back.skills, '{}'::jsonb))
       where coalesce((value->>'visible')::boolean, true)
         and (value->>'level')::int between 0 and 5
    ), '{}'::jsonb),
    'updated_at', back.updated_at
  );
end;
$$;


-- =============================================================
-- 管理者（Step 19）
-- 管理者の登録・解除のしかたは hikers-card-step19.sql の冒頭を参照
-- =============================================================

-- ---------- 管理者 ----------
create table public.admins (
  user_id    uuid primary key references auth.users(id) on delete cascade,
  role       text not null default 'koyaban' check (role in ('kanrinin', 'koyaban')),  -- 管理人／小屋番（Step 21）
  note       text,
  created_at timestamptz not null default now()
);

-- RLSを有効にし、ポリシーは作らない。
-- ＝画面（publishable キー）からは誰も読み書きできない。登録は SQL Editor からだけ。
alter table public.admins enable row level security;


-- ---------- ログイン中の人が管理者か ----------
create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.admins where user_id = auth.uid());
$$;


-- ---------- 検索条件に合うか（検索と件数で同じ条件を使うため、関数にまとめる） ----------
--   p_q    … 表示名・公開ID・メールアドレスの部分一致、タイプの完全一致、数字ならカードNo.
--   p_type … 'PGLA' などのタイプ、'none' で未診断のみ、空なら絞り込まない
create or replace function public.admin_user_matches(
  p_name text, p_public_id text, p_email text, p_type_code text, p_card_no int,
  p_q text, p_type text)
returns boolean language sql immutable as $$
  select
    (p_q is null
      or p_name      ilike '%' || p_q || '%' escape '\'
      or p_public_id ilike '%' || p_q || '%' escape '\'
      or p_email     ilike '%' || p_q || '%' escape '\'
      or upper(coalesce(p_type_code, '')) = upper(p_q)
      or (p_q ~ '^[0-9]{1,9}$' and p_card_no = p_q::int))
    and
    (p_type is null
      or (p_type = 'none' and p_type_code is null)
      or p_type_code = upper(p_type));
$$;


-- ---------- ユーザー検索 ----------
--   p_sort … 'new'（登録が新しい順）/ 'old' / 'no'（カードNo.順）/ 'name'（表示名順）
--   返すもの：{ total: 条件に合う人数, all: 全ユーザー数, items: [...] }
create or replace function public.admin_search_users(
  p_query  text default null,
  p_type   text default null,
  p_sort   text default 'new',
  p_limit  int  default 50,
  p_offset int  default 0)
returns jsonb language plpgsql stable security definer set search_path = public, auth as $$
declare
  q    text := nullif(btrim(coalesce(p_query, '')), '');
  t    text := nullif(btrim(coalesce(p_type, '')), '');
  lim  int  := least(greatest(coalesce(p_limit, 50), 1), 200);
  off  int  := greatest(coalesce(p_offset, 0), 0);
  total int;
  allc  int;
  items jsonb;
  my_role text := public.my_admin_role();
  see_email boolean;
begin
  -- 管理人・小屋番でなければ何も返さない
  if my_role is null then
    raise exception 'forbidden';
  end if;
  -- メールアドレスは管理人だけが見られる（小屋番はメールで検索することもできない）
  see_email := my_role = 'kanrinin';

  -- LIKE の特殊文字（% と _）を、ふつうの文字として探せるようにする
  if q is not null then
    q := replace(replace(replace(q, '\', '\\'), '%', '\%'), '_', '\_');
  end if;

  select count(*) into allc from public.profiles;

  select count(*) into total
    from public.profiles p join auth.users u on u.id = p.id
   where public.admin_user_matches(p.display_name, p.public_id, case when see_email then u.email end, p.type_code, p.card_no, q, t);

  select coalesce(jsonb_agg(row_to_json(r)::jsonb), '[]'::jsonb) into items
  from (
    select
      p.public_id, p.card_no, p.display_name, p.type_code,
      case when see_email then u.email end as email,
      p.created_at, u.last_sign_in_at,
      (select count(*) from public.climbed_mountains c where c.user_id = p.id) as climbed,
      (select count(*) from public.exchanges e where p.id in (e.user_a, e.user_b)) as exchanges,
      (select count(*) from public.reports rp where rp.reported_id = p.id and rp.status = 'open') as reports_open,
      (select a.role from public.admins a where a.user_id = p.id) as role,
      p.id = auth.uid() as is_me,
      p.is_tester
    from public.profiles p join auth.users u on u.id = p.id
    where public.admin_user_matches(p.display_name, p.public_id, case when see_email then u.email end, p.type_code, p.card_no, q, t)
    order by
      case when p_sort = 'old'  then p.created_at end asc,
      case when p_sort = 'no'   then p.card_no end asc,
      case when p_sort = 'name' then nullif(p.display_name, '') end asc nulls last,
      case when p_sort = 'login' then u.last_sign_in_at end desc nulls last,
      p.created_at desc
    limit lim offset off
  ) r;

  return jsonb_build_object('total', total, 'all', allc, 'items', items, 'my_role', my_role);
end;
$$;


-- =============================================================
-- 管理人・小屋番（Step 21）
-- =============================================================

create or replace function public.my_admin_role()
returns text language sql stable security definer set search_path = public as $$
  select role from public.admins where user_id = auth.uid();
$$;

create or replace function public.admin_set_koyaban(p_public_id text, p_on boolean)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  target uuid;
  cur    text;
begin
  if public.my_admin_role() is distinct from 'kanrinin' then
    raise exception 'forbidden';
  end if;

  select id into target from public.profiles where public_id = p_public_id;
  if target is null then return jsonb_build_object('ok', false, 'reason', 'not_found'); end if;
  if target = auth.uid() then return jsonb_build_object('ok', false, 'reason', 'self'); end if;

  select role into cur from public.admins where user_id = target;
  if cur = 'kanrinin' then return jsonb_build_object('ok', false, 'reason', 'kanrinin'); end if;

  if p_on then
    insert into public.admins (user_id, role, note)
    values (target, 'koyaban', '管理人が付与')
    on conflict (user_id) do nothing;
  else
    delete from public.admins where user_id = target and role = 'koyaban';
  end if;

  return jsonb_build_object('ok', true, 'role', case when p_on then 'koyaban' end);
end;
$$;


-- =============================================================
-- カード交換のお知らせ（Step 21）
-- ※ redeem_exchange_token がこの表に書き込む
-- =============================================================

create table public.notices (
  id         bigint generated always as identity primary key,
  user_id    uuid not null references public.profiles(id) on delete cascade,
  kind       text not null check (kind in ('exchanged')),
  partner_id uuid references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  seen_at    timestamptz
);
create index notices_unseen_idx on public.notices (user_id) where seen_at is null;

-- 画面からは直接読み書きさせない（take_my_notices 経由だけ）
alter table public.notices enable row level security;

create or replace function public.take_my_notices()
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  result jsonb;
begin
  if me is null then return '[]'::jsonb; end if;

  select coalesce(jsonb_agg(jsonb_build_object(
      'kind', n.kind,
      'created_at', n.created_at,
      'partner', jsonb_build_object(
        'public_id', p.public_id,
        'display_name', p.display_name,
        'type_code', p.type_code))
      order by n.created_at desc), '[]'::jsonb)
    into result
    from public.notices n
    join public.profiles p on p.id = n.partner_id
   where n.user_id = me and n.seen_at is null
     and not exists (
       select 1 from public.blocks b
        where (b.blocker_id = me and b.blocked_id = p.id)
           or (b.blocker_id = p.id and b.blocked_id = me));

  update public.notices set seen_at = now()
   where user_id = me and seen_at is null;

  return result;
end;
$$;


-- =============================================================
-- カードづくり（Step 23）
-- =============================================================

create or replace function public.complete_onboarding()
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me    uuid := auth.uid();
  prof  public.profiles%rowtype;
  n_climbed int;
  n_fav     int;
  n_wish    int;
begin
  if me is null then raise exception 'not authenticated'; end if;

  select * into prof from public.profiles where id = me;
  if not found then raise exception 'no profile'; end if;

  -- すでに完成していれば、そのまま番号を返す
  if prof.onboarded_at is not null then
    return jsonb_build_object('ok', true, 'card_no', prof.card_no, 'already', true);
  end if;

  if coalesce(btrim(prof.display_name), '') = '' then
    return jsonb_build_object('ok', false, 'reason', 'no_name');
  end if;
  if prof.type_code is null then
    return jsonb_build_object('ok', false, 'reason', 'no_type');
  end if;

  select count(*), count(*) filter (where is_favorite)
    into n_climbed, n_fav
    from public.climbed_mountains where user_id = me;
  select count(*) into n_wish from public.wishlist_mountains where user_id = me;

  if n_wish < 1 then
    return jsonb_build_object('ok', false, 'reason', 'no_wish');
  end if;
  if n_climbed > 0 and n_fav < 1 then
    return jsonb_build_object('ok', false, 'reason', 'no_fav');
  end if;

  -- 完成の日時を記録（保護トリガーに許可の印を見せる）。トリガーが番号を振る
  perform set_config('hc.onboarding', '1', true);
  update public.profiles set onboarded_at = now() where id = me;
  perform set_config('hc.onboarding', '', true);

  select * into prof from public.profiles where id = me;
  return jsonb_build_object('ok', true, 'card_no', prof.card_no);
end;
$$;


-- =============================================================
-- テスト用アカウント（Step 24）
-- =============================================================

create or replace function public.admin_set_tester(p_public_id text, p_on boolean)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  target uuid;
begin
  if public.my_admin_role() is distinct from 'kanrinin' then
    raise exception 'forbidden';
  end if;

  select id into target from public.profiles where public_id = p_public_id;
  if target is null then return jsonb_build_object('ok', false, 'reason', 'not_found'); end if;

  perform set_config('hc.tester', '1', true);
  update public.profiles set is_tester = coalesce(p_on, false) where id = target;
  perform set_config('hc.tester', '', true);

  return jsonb_build_object('ok', true, 'is_tester', coalesce(p_on, false));
end;
$$;

create or replace function public.reset_my_onboarding()
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
begin
  if me is null then raise exception 'not authenticated'; end if;

  -- テスト用でなければ使えない（一般の利用者は絶対にやり直せない）
  if not coalesce((select is_tester from public.profiles where id = me), false) then
    raise exception 'forbidden';
  end if;

  delete from public.climbed_mountains where user_id = me;
  delete from public.wishlist_mountains where user_id = me;

  -- 完成の記録も消す（保護トリガーに許可の印を見せる）。カード番号は残す
  perform set_config('hc.onboarding', '1', true);
  update public.profiles
     set display_name = '', comment = null, card_bg = 'snow',
         type_code = null, axis_pe = null, axis_sg = null, axis_lf = null, axis_ca = null,
         onboarded_at = null
   where id = me;
  perform set_config('hc.onboarding', '', true);

  return jsonb_build_object('ok', true);
end;
$$;
