-- =============================================================
-- ハイカーズカード 現行スキーマ（2026-09-28 本番DBから復元 ＋ Step 17 適用後）
--
-- 本番の Supabase から書き出した定義をもとに、1本にまとめたもの。
-- これまでの差分SQL（phase15 / report-block / mountains-* / affinity /
-- fix-favorite など）と step17 をすべて適用した後の状態に相当する。
--
-- 用途：
--   ・今後の開発の「正」となる参照資料
--   ・新しい環境（検証用プロジェクトなど）を空の状態から作るとき
--
-- ※ 本番DBには実行しないこと。すでに存在するため、トリガーや
--    ポリシーの作成でエラーになる。本番の変更は差分SQLで行う。
-- ※ 山マスタ349座のデータは含まない（別途 Table Editor から
--    CSVで書き出して取り込む）。
-- =============================================================


-- ---------- ランダム文字列 ----------

-- 公開ID用（紛らわしい文字 l/1/o/0 を除いた31文字）
create or replace function public.random_public_id(len integer default 6)
returns text language sql as $$
  select string_agg(
    substr('abcdefghjkmnpqrstuvwxyz23456789',
           (floor(random() * 31) + 1)::int, 1), '')
  from generate_series(1, len);
$$;

-- 交換トークン用（英数字62文字）
create or replace function public.random_token(len integer default 16)
returns text language sql as $$
  select string_agg(
    substr('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789',
           (floor(random() * 62) + 1)::int, 1), '')
  from generate_series(1, len);
$$;


-- =============================================================
-- テーブル
-- =============================================================

-- ---------- 山マスタ（349座） ----------
create table public.mountains (
  id          smallint generated by default as identity primary key,
  name        text not null unique,
  kana        text not null,
  elevation   smallint,
  area        text,
  difficulty  smallint check (difficulty between 1 and 5),
  meizan_rank smallint check (meizan_rank in (100, 200, 300)),  -- null = その他
  region      text check (region in (
                'north', 'kita_alps', 'minami_alps', 'koshin',
                'kanto', 'tokai', 'west')),
  is_popular  boolean not null default false,
  prefs       text[] not null default '{}',   -- 都道府県（県境の山は複数）
  pref        text                             -- 旧列。コードからは未使用
);
create index mountains_kana_idx    on public.mountains (kana);
create index mountains_rank_idx    on public.mountains (meizan_rank);
create index mountains_region_idx  on public.mountains (region);
create index mountains_popular_idx on public.mountains (is_popular) where is_popular;

-- ---------- プロフィール（カードの中身） ----------
create table public.profiles (
  id            uuid primary key references auth.users(id) on delete cascade,
  public_id     text not null unique,
  card_no       integer generated by default as identity not null,
  display_name  text not null default '' check (char_length(display_name) <= 20),
  comment       text check (char_length(comment) <= 120),
  type_code     text check (type_code ~ '^[A-Z]{4}$'),
  axis_pe       smallint check (axis_pe between 0 and 100),
  axis_sg       smallint check (axis_sg between 0 and 100),
  axis_lf       smallint check (axis_lf between 0 and 100),
  axis_ca       smallint check (axis_ca between 0 and 100),
  card_bg       text not null default 'contour'
                  check (card_bg in ('contour', 'ridge', 'mist', 'forest', 'night')),
  sns_yamap     text check (char_length(sns_yamap)     <= 60),
  sns_yamareco  text check (char_length(sns_yamareco)  <= 60),
  sns_instagram text check (char_length(sns_instagram) <= 60),
  sns_x         text check (char_length(sns_x)         <= 60),
  vis_rank_100  boolean not null default true,
  vis_rank_200  boolean not null default true,
  vis_rank_300  boolean not null default true,
  vis_rank_other boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create unique index profiles_card_no_idx on public.profiles (card_no);

-- ---------- 登った山（is_favorite = 行ってよかった山） ----------
create table public.climbed_mountains (
  user_id     uuid not null references public.profiles(id) on delete cascade,
  mountain_id smallint not null references public.mountains(id),
  is_favorite boolean not null default false,
  favorite_rank smallint check (favorite_rank between 1 and 5),   -- よかった山の順位
  created_at  timestamptz not null default now(),
  primary key (user_id, mountain_id)
);
create index climbed_favorite_idx on public.climbed_mountains (user_id) where is_favorite;
create unique index climbed_favorite_rank_uniq
  on public.climbed_mountains (user_id, favorite_rank) where favorite_rank is not null;

-- ---------- 登りたい山 ----------
create table public.wishlist_mountains (
  user_id     uuid not null references public.profiles(id) on delete cascade,
  mountain_id smallint not null references public.mountains(id),
  created_at  timestamptz not null default now(),
  primary key (user_id, mountain_id)
);

-- ---------- 交換トークン（10分有効のQR） ----------
create table public.exchange_tokens (
  token      text primary key,
  owner_id   uuid not null references public.profiles(id) on delete cascade,
  expires_at timestamptz not null,
  revoked    boolean not null default false,
  use_count  integer not null default 0,
  created_at timestamptz not null default now()
);
create index exchange_tokens_owner_idx on public.exchange_tokens (owner_id);

-- ---------- 交換の記録（1組1行、user_a < user_b） ----------
create table public.exchanges (
  id                uuid primary key default gen_random_uuid(),
  user_a            uuid not null references public.profiles(id) on delete cascade,
  user_b            uuid not null references public.profiles(id) on delete cascade,
  first_met_at      timestamptz not null default now(),
  last_exchanged_at timestamptz not null default now(),
  check (user_a < user_b),
  unique (user_a, user_b)
);

-- ---------- ブロック ----------
create table public.blocks (
  blocker_id uuid not null references public.profiles(id) on delete cascade,
  blocked_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (blocker_id, blocked_id),
  check (blocker_id <> blocked_id)
);

-- ---------- 通報 ----------
create table public.reports (
  id          uuid primary key default gen_random_uuid(),
  reporter_id uuid references public.profiles(id) on delete set null,
  reported_id uuid not null references public.profiles(id) on delete cascade,
  reason      text not null,
  detail      text check (char_length(detail) <= 1000),
  status      text not null default 'open' check (status in ('open', 'resolved')),
  created_at  timestamptz not null default now()
);


-- =============================================================
-- RLS とポリシー
-- =============================================================

alter table public.mountains          enable row level security;
alter table public.profiles           enable row level security;
alter table public.climbed_mountains  enable row level security;
alter table public.wishlist_mountains enable row level security;
alter table public.exchange_tokens    enable row level security;
alter table public.exchanges          enable row level security;
alter table public.blocks             enable row level security;
alter table public.reports            enable row level security;

create policy "mountains readable" on public.mountains for select using (true);

create policy "own profile read"   on public.profiles for select using (auth.uid() = id);
create policy "own profile update" on public.profiles for update using (auth.uid() = id);

create policy "climbed read"   on public.climbed_mountains for select using (true);
create policy "climbed insert" on public.climbed_mountains for insert with check (auth.uid() = user_id);
create policy "climbed update" on public.climbed_mountains for update
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "climbed delete" on public.climbed_mountains for delete using (auth.uid() = user_id);

create policy "wishlist read"   on public.wishlist_mountains for select using (true);
create policy "wishlist insert" on public.wishlist_mountains for insert with check (auth.uid() = user_id);
create policy "wishlist update" on public.wishlist_mountains for update
  using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "wishlist delete" on public.wishlist_mountains for delete using (auth.uid() = user_id);

create policy "token read"   on public.exchange_tokens for select using (auth.uid() = owner_id);
create policy "token insert" on public.exchange_tokens for insert with check (auth.uid() = owner_id);
create policy "token revoke" on public.exchange_tokens for update using (auth.uid() = owner_id);

create policy "exchange read"   on public.exchanges for select
  using (auth.uid() = user_a or auth.uid() = user_b);
create policy "exchange delete" on public.exchanges for delete
  using (auth.uid() = user_a or auth.uid() = user_b);

create policy "blocks read"   on public.blocks for select using (auth.uid() = blocker_id);
create policy "blocks insert" on public.blocks for insert with check (auth.uid() = blocker_id);
create policy "blocks delete" on public.blocks for delete using (auth.uid() = blocker_id);

create policy "reports insert" on public.reports for insert
  with check (reporter_id is null or auth.uid() = reporter_id);


-- =============================================================
-- トリガー関数とトリガー
-- =============================================================

-- アカウント作成時に profiles 行を自動作成
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
declare new_id text;
begin
  loop
    new_id := public.random_public_id(6);
    exit when not exists (select 1 from public.profiles where public_id = new_id);
  end loop;
  insert into public.profiles (id, public_id) values (new.id, new_id);
  return new;
end;
$$;

-- ※ auth スキーマ側のトリガーなので、今回の書き出しには出ていない。
--    設計書 v1 の定義どおり存在する前提。
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 変更不可列の保護 ＋ updated_at 自動更新
create or replace function public.protect_profile_fields()
returns trigger language plpgsql as $$
begin
  new.updated_at := now();
  new.public_id  := old.public_id;   -- URLは変更不可
  new.card_no    := old.card_no;     -- カード番号も変更不可
  new.created_at := old.created_at;
  return new;
end;
$$;

create trigger on_profile_update
  before update on public.profiles
  for each row execute function public.protect_profile_fields();

-- 行ってよかった山は5座まで
create or replace function public.limit_favorites()
returns trigger language plpgsql as $$
begin
  if new.is_favorite and (
    select count(*) from public.climbed_mountains
     where user_id = new.user_id and is_favorite
       and mountain_id <> new.mountain_id
  ) >= 5 then
    raise exception 'favorite_limit';
  end if;
  return new;
end;
$$;

create trigger check_favorite_limit
  before insert or update on public.climbed_mountains
  for each row execute function public.limit_favorites();

-- 登りたい山は5座まで
create or replace function public.limit_wishlist()
returns trigger language plpgsql as $$
begin
  if (select count(*) from public.wishlist_mountains
       where user_id = new.user_id) >= 5 then
    raise exception 'wishlist_limit';
  end if;
  return new;
end;
$$;

create trigger check_wishlist_limit
  before insert on public.wishlist_mountains
  for each row execute function public.limit_wishlist();

-- ブロックしたら交換記録を削除
create or replace function public.on_block_created()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  delete from public.exchanges
   where (user_a = least(new.blocker_id, new.blocked_id)
      and user_b = greatest(new.blocker_id, new.blocked_id));
  return new;
end;
$$;

create trigger after_block_insert
  after insert on public.blocks
  for each row execute function public.on_block_created();


-- =============================================================
-- RPC
-- =============================================================

-- ---------- 名山ランク別の踏破数 ----------
create or replace function public.meizan_counts(p_user uuid)
returns jsonb language sql stable security definer set search_path = public as $$
  select jsonb_build_object(
    '100',   count(*) filter (where m.meizan_rank = 100),
    '200',   count(*) filter (where m.meizan_rank = 200),
    '300',   count(*) filter (where m.meizan_rank = 300),
    'other', count(*) filter (where m.meizan_rank is null)
  )
  from public.climbed_mountains c
  join public.mountains m on m.id = c.mountain_id
  where c.user_id = p_user;
$$;

-- ---------- 自分のカード（共通点の計算用） ----------
create or replace function public.get_my_card()
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  prof public.profiles%rowtype;
  cnt jsonb;
begin
  if me is null then return null; end if;

  select * into prof from public.profiles where id = me;
  if not found then return null; end if;

  cnt := public.meizan_counts(me);

  return jsonb_build_object(
    'public_id',    prof.public_id,
    'card_no',      prof.card_no,
    'display_name', prof.display_name,
    'comment',      prof.comment,
    'type_code',    prof.type_code,
    'card_bg',      prof.card_bg,
    'axes', jsonb_build_object(
      'pe', prof.axis_pe, 'sg', prof.axis_sg,
      'lf', prof.axis_lf, 'ca', prof.axis_ca),
    'ranks', cnt,
    'climbed',
      coalesce((select jsonb_agg(jsonb_build_object(
          'name', m.name, 'rank', m.meizan_rank)
          order by m.elevation desc nulls last)
        from public.climbed_mountains c
        join public.mountains m on m.id = c.mountain_id
       where c.user_id = me), '[]'::jsonb),
    'favorites',
      coalesce((select jsonb_agg(jsonb_build_object(
          'name', m.name, 'rank', m.meizan_rank, 'pos', c.favorite_rank)
          order by c.favorite_rank nulls last, m.elevation desc nulls last)
        from public.climbed_mountains c
        join public.mountains m on m.id = c.mountain_id
       where c.user_id = me and c.is_favorite), '[]'::jsonb),
    'wishlist',
      coalesce((select jsonb_agg(jsonb_build_object(
          'name', m.name, 'rank', m.meizan_rank)
          order by m.elevation desc nulls last)
        from public.wishlist_mountains w
        join public.mountains m on m.id = w.mountain_id
       where w.user_id = me), '[]'::jsonb)
  );
end;
$$;

-- ---------- 公開カード ----------
create or replace function public.get_public_card(p_public_id text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  prof public.profiles%rowtype;
  viewer uuid := auth.uid();
  result jsonb;
  sns jsonb;
  cnt jsonb;
  ranks jsonb;
begin
  select * into prof from public.profiles where public_id = p_public_id;
  if not found then return null; end if;
  if prof.display_name = '' then return null; end if;

  -- 相手にブロックされていたら「存在しない」ことにする
  if viewer is not null and exists (
    select 1 from public.blocks
    where blocker_id = prof.id and blocked_id = viewer
  ) then
    return null;
  end if;

  -- SNSは入力のあるものだけ返す
  sns := '{}'::jsonb;
  if nullif(btrim(coalesce(prof.sns_yamap,     '')), '') is not null then
    sns := sns || jsonb_build_object('yamap', prof.sns_yamap); end if;
  if nullif(btrim(coalesce(prof.sns_yamareco,  '')), '') is not null then
    sns := sns || jsonb_build_object('yamareco', prof.sns_yamareco); end if;
  if nullif(btrim(coalesce(prof.sns_instagram, '')), '') is not null then
    sns := sns || jsonb_build_object('instagram', prof.sns_instagram); end if;
  if nullif(btrim(coalesce(prof.sns_x,         '')), '') is not null then
    sns := sns || jsonb_build_object('x', prof.sns_x); end if;

  -- 踏破数。公開設定がオンのものだけ含める
  cnt := public.meizan_counts(prof.id);
  ranks := '{}'::jsonb;
  if prof.vis_rank_100   then ranks := ranks || jsonb_build_object('100',   cnt->'100');   end if;
  if prof.vis_rank_200   then ranks := ranks || jsonb_build_object('200',   cnt->'200');   end if;
  if prof.vis_rank_300   then ranks := ranks || jsonb_build_object('300',   cnt->'300');   end if;
  if prof.vis_rank_other then ranks := ranks || jsonb_build_object('other', cnt->'other'); end if;

  result := jsonb_build_object(
    'public_id',    prof.public_id,
    'card_no',      prof.card_no,
    'display_name', prof.display_name,
    'comment',      prof.comment,
    'type_code',    prof.type_code,
    'card_bg',      prof.card_bg,
    'axes', jsonb_build_object(
      'pe', prof.axis_pe, 'sg', prof.axis_sg,
      'lf', prof.axis_lf, 'ca', prof.axis_ca),
    'sns', sns,
    'ranks', ranks,
    'climbed',
      coalesce((select jsonb_agg(jsonb_build_object(
          'name', m.name, 'rank', m.meizan_rank)
          order by m.elevation desc nulls last)
        from public.climbed_mountains c
        join public.mountains m on m.id = c.mountain_id
       where c.user_id = prof.id), '[]'::jsonb),
    'favorites',
      coalesce((select jsonb_agg(jsonb_build_object(
          'name', m.name, 'rank', m.meizan_rank, 'pos', c.favorite_rank)
          order by c.favorite_rank nulls last, m.elevation desc nulls last)
        from public.climbed_mountains c
        join public.mountains m on m.id = c.mountain_id
       where c.user_id = prof.id and c.is_favorite), '[]'::jsonb),
    'wishlist',
      coalesce((select jsonb_agg(jsonb_build_object(
          'name', m.name, 'rank', m.meizan_rank)
          order by m.elevation desc nulls last)
        from public.wishlist_mountains w
        join public.mountains m on m.id = w.mountain_id
       where w.user_id = prof.id), '[]'::jsonb)
  );

  if viewer is not null and viewer <> prof.id then
    result := result || jsonb_build_object('exchanged', exists (
      select 1 from public.exchanges
      where user_a = least(viewer, prof.id) and user_b = greatest(viewer, prof.id)));
  end if;

  return result;
end;
$$;

-- ---------- コレクション ----------
create or replace function public.get_my_collection()
returns jsonb language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid();
begin
  if me is null then raise exception 'not authenticated'; end if;

  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'public_id',    p.public_id,
      'card_no',      p.card_no,
      'display_name', p.display_name,
      'comment',      p.comment,
      'type_code',    p.type_code,
      'card_bg',      p.card_bg,
      'axes', jsonb_build_object(
        'pe', p.axis_pe, 'sg', p.axis_sg, 'lf', p.axis_lf, 'ca', p.axis_ca),
      'sns', (
        select coalesce(jsonb_object_agg(k, v), '{}'::jsonb)
        from (values
          ('yamap', p.sns_yamap), ('yamareco', p.sns_yamareco),
          ('instagram', p.sns_instagram), ('x', p.sns_x)
        ) as t(k, v)
        where nullif(btrim(coalesce(v, '')), '') is not null),
      'ranks', (
        select coalesce(jsonb_object_agg(k, v), '{}'::jsonb)
        from (values
          ('100',   case when p.vis_rank_100   then public.meizan_counts(p.id)->'100'   end),
          ('200',   case when p.vis_rank_200   then public.meizan_counts(p.id)->'200'   end),
          ('300',   case when p.vis_rank_300   then public.meizan_counts(p.id)->'300'   end),
          ('other', case when p.vis_rank_other then public.meizan_counts(p.id)->'other' end)
        ) as t(k, v)
        where v is not null),
      'climbed',
        coalesce((select jsonb_agg(jsonb_build_object(
            'name', m.name, 'rank', m.meizan_rank)
            order by m.elevation desc nulls last)
          from public.climbed_mountains c
          join public.mountains m on m.id = c.mountain_id
         where c.user_id = p.id), '[]'::jsonb),
      'favorites',
        coalesce((select jsonb_agg(jsonb_build_object(
            'name', m.name, 'rank', m.meizan_rank, 'pos', c.favorite_rank)
            order by c.favorite_rank nulls last, m.elevation desc nulls last)
          from public.climbed_mountains c
          join public.mountains m on m.id = c.mountain_id
         where c.user_id = p.id and c.is_favorite), '[]'::jsonb),
      'wishlist',
        coalesce((select jsonb_agg(jsonb_build_object(
            'name', m.name, 'rank', m.meizan_rank)
            order by m.elevation desc nulls last)
          from public.wishlist_mountains w
          join public.mountains m on m.id = w.mountain_id
         where w.user_id = p.id), '[]'::jsonb),
      'first_met_at', e.first_met_at
    ) order by e.first_met_at desc)
    from public.exchanges e
    join public.profiles p
      on p.id = case when e.user_a = me then e.user_b else e.user_a end
   where me in (e.user_a, e.user_b)
  ), '[]'::jsonb);
end;
$$;

-- ---------- 山の登録をまとめて保存（Step 17） ----------
-- p_favorites は配列の順番がそのまま1位〜5位
create or replace function public.save_my_mountains(
  p_climbed   smallint[],
  p_favorites smallint[],
  p_wishlist  smallint[])
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me   uuid := auth.uid();
  clim smallint[];
  fav  smallint[];
  wish smallint[];
begin
  if me is null then raise exception 'not authenticated'; end if;

  -- 重複を除く（よかった山は順番を保つ）
  select coalesce(array_agg(distinct x), '{}') into clim
    from unnest(coalesce(p_climbed, '{}')) as x;

  select coalesce(array_agg(x order by first_pos), '{}') into fav
    from (select x, min(ord) as first_pos
            from unnest(coalesce(p_favorites, '{}')) with ordinality as t(x, ord)
           group by x) s;

  select coalesce(array_agg(distinct x), '{}') into wish
    from unnest(coalesce(p_wishlist, '{}')) as x;

  -- 検証
  if cardinality(fav) > 5 then raise exception 'favorite_limit'; end if;
  if cardinality(wish) > 5 then raise exception 'wishlist_limit'; end if;
  if not (fav <@ clim) then raise exception 'favorite_not_climbed'; end if;

  -- 登りたい山のうち、登った山に入っているものは外す
  select coalesce(array_agg(x), '{}') into wish
    from unnest(wish) as x where x <> all(clim);

  -- 登った山：外したものを消し、足したものを入れる
  delete from public.climbed_mountains
   where user_id = me and mountain_id <> all(clim);

  insert into public.climbed_mountains (user_id, mountain_id)
  select me, x from unnest(clim) as x
  on conflict (user_id, mountain_id) do nothing;

  -- よかった山：いったん全部外してから、順位を付け直す
  update public.climbed_mountains
     set is_favorite = false, favorite_rank = null
   where user_id = me and (is_favorite or favorite_rank is not null);

  update public.climbed_mountains c
     set is_favorite = true, favorite_rank = f.ord
    from unnest(fav) with ordinality as f(id, ord)
   where c.user_id = me and c.mountain_id = f.id;

  -- 登りたい山：入れ直す
  delete from public.wishlist_mountains where user_id = me;

  insert into public.wishlist_mountains (user_id, mountain_id)
  select me, x from unnest(wish) as x;

  return jsonb_build_object(
    'ok', true,
    'climbed', cardinality(clim),
    'favorites', cardinality(fav),
    'wishlist', cardinality(wish));
end;
$$;

-- ---------- 交換トークンの発行 ----------
create or replace function public.issue_exchange_token()
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  t text;
  exp timestamptz := now() + interval '10 minutes';
begin
  if me is null then raise exception 'not authenticated'; end if;

  -- 表示名が未設定のうちは交換できない
  if (select display_name from public.profiles where id = me) = '' then
    raise exception 'profile not ready';
  end if;

  -- 既存の有効なトークンを無効化（同時に複数出さない）
  update public.exchange_tokens
     set revoked = true
   where owner_id = me and revoked = false and expires_at > now();

  loop
    t := public.random_token(16);
    exit when not exists (select 1 from public.exchange_tokens where token = t);
  end loop;

  insert into public.exchange_tokens (token, owner_id, expires_at)
  values (t, me, exp);

  return jsonb_build_object('token', t, 'expires_at', exp);
end;
$$;

-- ---------- 交換トークンの使用 ----------
create or replace function public.redeem_exchange_token(p_token text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me uuid := auth.uid();
  tok public.exchange_tokens%rowtype;
  a uuid; b uuid;
  is_new boolean;
begin
  if me is null then raise exception 'not authenticated'; end if;

  select * into tok from public.exchange_tokens where token = p_token;
  if not found then return jsonb_build_object('ok', false, 'reason', 'not_found'); end if;
  if tok.revoked then return jsonb_build_object('ok', false, 'reason', 'revoked'); end if;
  if tok.expires_at <= now() then return jsonb_build_object('ok', false, 'reason', 'expired'); end if;
  if tok.owner_id = me then return jsonb_build_object('ok', false, 'reason', 'self'); end if;

  -- どちらかがブロックしていたら交換できない
  if exists (
    select 1 from public.blocks
    where (blocker_id = tok.owner_id and blocked_id = me)
       or (blocker_id = me and blocked_id = tok.owner_id)
  ) then
    return jsonb_build_object('ok', false, 'reason', 'blocked');
  end if;

  -- 表示名が未設定なら交換できない
  if (select display_name from public.profiles where id = me) = '' then
    return jsonb_build_object('ok', false, 'reason', 'profile_not_ready');
  end if;

  a := least(me, tok.owner_id);
  b := greatest(me, tok.owner_id);

  insert into public.exchanges (user_a, user_b)
  values (a, b)
  on conflict (user_a, user_b)
    do update set last_exchanged_at = now()   -- first_met_at は上書きしない
  returning (xmax = 0) into is_new;

  update public.exchange_tokens
     set use_count = use_count + 1
   where token = p_token;

  return jsonb_build_object(
    'ok', true,
    'is_new', is_new,
    'partner', (select public_id from public.profiles where id = tok.owner_id));
end;
$$;

-- ---------- 通報（あわせてブロックも可） ----------
create or replace function public.submit_report(
  p_public_id text, p_reason text,
  p_detail text default null, p_block boolean default false)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me     uuid := auth.uid();
  target uuid;
begin
  select id into target from public.profiles where public_id = p_public_id;
  if target is null then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;

  if me is not null and me = target then
    return jsonb_build_object('ok', false, 'reason', 'self');
  end if;

  if p_reason is null or btrim(p_reason) = '' then
    return jsonb_build_object('ok', false, 'reason', 'no_reason');
  end if;

  insert into public.reports (reporter_id, reported_id, reason, detail)
  values (me, target, p_reason, nullif(btrim(coalesce(p_detail, '')), ''));

  -- あわせてブロックする場合（ログインしているときだけ）
  if p_block and me is not null then
    insert into public.blocks (blocker_id, blocked_id)
    values (me, target)
    on conflict do nothing;
  end if;

  return jsonb_build_object('ok', true);
end;
$$;

-- ---------- ブロック ----------
create or replace function public.block_user(p_public_id text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me     uuid := auth.uid();
  target uuid;
begin
  if me is null then
    return jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  end if;

  select id into target from public.profiles where public_id = p_public_id;
  if target is null then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;
  if target = me then
    return jsonb_build_object('ok', false, 'reason', 'self');
  end if;

  insert into public.blocks (blocker_id, blocked_id)
  values (me, target)
  on conflict do nothing;

  return jsonb_build_object('ok', true);
end;
$$;

-- ---------- ブロック解除 ----------
create or replace function public.unblock_user(p_public_id text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  me     uuid := auth.uid();
  target uuid;
begin
  if me is null then
    return jsonb_build_object('ok', false, 'reason', 'not_authenticated');
  end if;

  select id into target from public.profiles where public_id = p_public_id;
  if target is null then
    return jsonb_build_object('ok', false, 'reason', 'not_found');
  end if;

  delete from public.blocks
   where blocker_id = me and blocked_id = target;

  return jsonb_build_object('ok', true);
end;
$$;

-- ---------- ブロック中の一覧 ----------
create or replace function public.get_my_blocks()
returns jsonb language plpgsql security definer set search_path = public as $$
declare me uuid := auth.uid();
begin
  if me is null then
    raise exception 'not authenticated';
  end if;

  return coalesce((
    select jsonb_agg(jsonb_build_object(
      'public_id',    p.public_id,
      'display_name', p.display_name,
      'type_code',    p.type_code,
      'card_no',      p.card_no,
      'blocked_at',   b.created_at
    ) order by b.created_at desc)
    from public.blocks b
    join public.profiles p on p.id = b.blocked_id
   where b.blocker_id = me
  ), '[]'::jsonb);
end;
$$;

-- （参考）rls_auto_enable は Supabase が自動で用意する関数で、
--  public に作ったテーブルのRLSを自動で有効にするもの。自作ではないので含めていない。
